# Generated by Django 3.2.6 on 2021-10-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='send_message',
            new_name='send_messages',
        ),
    ]
